### ISSUE TITLE
KeyError: 'ints'

### ISSUE THREAD

**Issue by yangshihao-arron** [zhaoyingjun/chatbot#105]
您好，我下载了这个代码，准备学习下tf2这个版本，我把train_data文件夹下的数据集按照要求放到新建的data文件夹下，运行data_util.py，一直报错，新手不是很理解。
Traceback (most recent call last):
  File "G:\code_software\anaconda\envs\python35\lib\configparser.py", line 843, in items
    d.update(self._sections[section])
KeyError: 'ints'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/python/chineseChatbotWeb-tf2.0/seq2seqChatbot/data_util.py", line 13, in <module>
    gConfig=getConfig.get_config()
  File "D:\python\chineseChatbotWeb-tf2.0\seq2seqChatbot\getConfig.py", line 9, in get_config
    _conf_ints = [ (key, int(value)) for key,value in parser.items('ints') ]
  File "G:\code_software\anaconda\envs\python35\lib\configparser.py", line 846, in items
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'ints'

**Comment by Saturn24** [comment]
我也遇到这个问题了，请问解决掉了么

**Comment by Saturn24** [comment]
改一下getconfig.py这里（换成目录下有的ini文件名）
![image](https://user-images.githubusercontent.com/69412532/111311242-ee886800-8698-11eb-8d6d-13cb08d73daf.png)

**Comment by sunyrain** [comment]
改了以后还是没有用？

**Comment by NILIKUO** [comment]
+1，改了之后还是没用？

**Comment by liu1004010308** [comment]
+1
