### ISSUE TITLE
关于tensor2.0 ValueError: not enough values to unpack (expected 2, got 1) 有人解决了吗？

### ISSUE THREAD

**Issue by xzmlove** [zhaoyingjun/chatbot#123]
Traceback (most recent call last):
  File "D:/double d/python项目/chatbot-master/chatbot-master/chineseChatbotWeb-tf2.0/seq2seqChatbot/execute.py", line 55, in <module>
    input_tensor,input_token,target_tensor,target_token= read_data(gConfig['seq_data'], gConfig['max_train_data_size'])
  File "D:/double d/python项目/chatbot-master/chatbot-master/chineseChatbotWeb-tf2.0/seq2seqChatbot/execute.py", line 38, in read_data
    input_lang,target_lang=create_dataset(path,num_examples)
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by xzmlove** [comment]
path: D:\double d\python项目\chatbot-master\chatbot-master\chineseChatbotWeb-tf2.0\seq2seqChatbot\train_data\seq.data num_examples: 500000
这是我打印出来的两条信息

**Comment by xzmlove** [comment]
create_dataset(path,num_examples)之后打印出来看了一下，显示为<zip object at 0x000002892CAC2E08>

**Comment by xzmlove** [comment]
找到原因了，在data_util里面

**Comment by fengdys** [comment]
你好，这个bug你是怎么解决的，我按照你的好像还是没解决

**Comment by sunyrain** [comment]
seq.data的问题吧
