### ISSUE TITLE
'gbk' codec can't decode byte 0xad in position 107: illegal multibyte sequence

### ISSUE THREAD

**Issue by Chucy2020** [zhaoyingjun/chatbot#125]
出现一下问题，请问如何解决？

Traceback (most recent call last):
  File "D:/pycharm_code/test/chatbot-master/chineseChatbotWeb-pytorch/seq2seqChatbot/data_util.py", line 13, in <module>
    gConfig = getConfig.get_config()
  File "D:\pycharm_code\test\chatbot-master\chineseChatbotWeb-pytorch\seq2seqChatbot\getConfig.py", line 6, in get_config
    parser.read(config_file)
  File "C:\ProgramData\Anaconda3\lib\configparser.py", line 697, in read
    self._read(fp, filename)
  File "C:\ProgramData\Anaconda3\lib\configparser.py", line 1017, in _read
    for lineno, line in enumerate(fp, start=1):
UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 107: illegal multibyte sequence

**Comment by Merlin-xy** [comment]
我的也是这个问题..明明我已经声明了
#!/user/bin/python
# -*- coding:utf-8 -*-
哭了

**Comment by Merlin-xy** [comment]
```
#!/user/bin/python
# -*- coding:utf-8 -*-
```
明明我已经声明了，我也不知道为什么我也是这个问题，请问PO主找到解决方案了吗

**Comment by Merlin-xy** [comment]
> ```
> #!/user/bin/python
> # -*- coding:utf-8 -*-
> ```
> 
> 明明我已经声明了，我也不知道为什么我也是这个问题，请问PO主找到解决方案了吗

啊我改了一下getConfig.py第6行    parser.read(config_file,encoding='utf-8') 就可以运行了

**Comment by cmyopi** [comment]
ubuntu去跑
