### ISSUE TITLE
app.py无法正常使用

### ISSUE THREAD

**Issue by Ella-Alinda** [zhaoyingjun/chatbot#134]
* Serving Flask app "app" (lazy loading)                                                           [39/1867]
 * Environment: production                                                                                   
   WARNING: Do not use the development server in a production environment.         
   Use a production WSGI server instead.                                                                     
 * Debug mode: off                                    
 * Running on all addresses.                                                                                 
   WARNING: This is a development server. Do not use it in a production deployment.                          
 * Running on http://**************:8809/ (Press CTRL+C to quit)                                            
Building prefix dict from the default dictionary ...                                                         
Loading model from cache /tmp/jieba.cache                                                                    
Loading model cost 0.942 seconds.                                                                            
Prefix dict has been built successfully.                                                                     
[2022-06-23 22:31:06,778] ERROR in app: Exception on /message [POST]
Traceback (most recent call last):
  File "/home/ella/anaconda3/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ella/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ella/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ella/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/ella/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ella/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "web/app.py", line 43, in reply
    res_msg = execute.predict(req_msg)
AttributeError: module 'execute' has no attribute 'predict'

**Comment by paradox-11** [comment]
请问您现在解决了吗 我也碰到类似的情况

**Comment by Ella-Alinda** [comment]
暂时没有

**Comment by gitarya** [comment]
app.py import的execute是指上层的execute.py,不是pip install execute的这个包。在app.py最前面加上 sys.path.append("..")就可以了

**Comment by Fuji-021** [comment]
> app.py import的execute是指上层的execute.py,不是pip install execute的这个包。在app.py最前面加上 sys.path.append("..")就可以了

大佬，问一下我添加了这行代码，但是还是提示没有predict这个方法，是什么原因呢，麻烦您指教一下，非常感谢
