### ISSUE TITLE
请问，Could not find directory model_data，这个model_data在哪呢

### ISSUE THREAD

**Issue by lihongliang8955390** [zhaoyingjun/chatbot#143]
C:\Users\lenovo\anaconda3\python.exe D:/pythonProject/chatbot-master/Chatbot-tensowflow2.0/Seq2seqchatbot/execute.py
2022-09-02 15:51:23.531194: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
WARNING:tensorflow:From D:\pythonProject\chatbot-master\Chatbot-tensowflow2.0\Seq2seqchatbot\seq2seqModel.py:4: experimental_run_functions_eagerly (from tensorflow.python.eager.def_function) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.config.run_functions_eagerly` instead of the experimental version.
2022-09-02 15:51:27.261616: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library nvcuda.dll
2022-09-02 15:51:27.299469: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX 1050 computeCapability: 6.1
coreClock: 1.493GHz coreCount: 5 deviceMemorySize: 2.00GiB deviceMemoryBandwidth: 104.43GiB/s
2022-09-02 15:51:27.299871: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
2022-09-02 15:51:27.303435: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cublas64_10.dll
2022-09-02 15:51:27.306901: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cufft64_10.dll
2022-09-02 15:51:27.308988: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library curand64_10.dll
2022-09-02 15:51:27.313473: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusolver64_10.dll
2022-09-02 15:51:27.316951: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusparse64_10.dll
2022-09-02 15:51:27.325622: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudnn64_7.dll
2022-09-02 15:51:27.325904: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2022-09-02 15:51:27.326353: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-09-02 15:51:27.336508: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2175927da60 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2022-09-02 15:51:27.336909: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2022-09-02 15:51:27.337295: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX 1050 computeCapability: 6.1
coreClock: 1.493GHz coreCount: 5 deviceMemorySize: 2.00GiB deviceMemoryBandwidth: 104.43GiB/s
2022-09-02 15:51:27.337714: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
2022-09-02 15:51:27.337937: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cublas64_10.dll
2022-09-02 15:51:27.338201: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cufft64_10.dll
2022-09-02 15:51:27.338484: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library curand64_10.dll
2022-09-02 15:51:27.338733: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusolver64_10.dll
2022-09-02 15:51:27.338939: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusparse64_10.dll
2022-09-02 15:51:27.339151: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudnn64_7.dll
2022-09-02 15:51:27.339402: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2022-09-02 15:51:27.936912: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2022-09-02 15:51:27.937134: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0 
2022-09-02 15:51:27.937265: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N 
2022-09-02 15:51:27.937689: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 1327 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050, pci bus id: 0000:01:00.0, compute capability: 6.1)
2022-09-02 15:51:27.941064: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x21700242fb0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2022-09-02 15:51:27.941331: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce GTX 1050, Compute Capability 6.1
Traceback (most recent call last):
  File "D:/pythonProject/chatbot-master/Chatbot-tensowflow2.0/Seq2seqchatbot/execute.py", line 145, in <module>
    train()
  File "D:/pythonProject/chatbot-master/Chatbot-tensowflow2.0/Seq2seqchatbot/execute.py", line 66, in train
    ckpt=tf.io.gfile.listdir(checkpoint_dir)
  File "C:\Users\lenovo\anaconda3\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 691, in list_directory_v2
    raise errors.NotFoundError(
tensorflow.python.framework.errors_impl.NotFoundError: Could not find directory model_data

>> 执行器模式 : train

现在进行模型的训练
Preparing data in train_data
每个epoch的训练步数: 7095

**Comment by elvin-zheng** [comment]
同遇到
操作系统： mac OS
python version： Python 3.8.2
pip version： pip 22.2.2
```
现在进行模型的训练
Preparing data in train_data
每个epoch的训练步数: 7095
Traceback (most recent call last):
  File "execute.py", line 169, in <module>
    train()
  File "execute.py", line 81, in train
    ckpt = tf.io.gfile.listdir(checkpoint_dir)
  File "/Users/z_chong/Library/Python/3.8/lib/python/site-packages/tensorflow/python/lib/io/file_io.py", line 766, in list_directory_v2
    raise errors.NotFoundError(
tensorflow.python.framework.errors_impl.NotFoundError: Could not find directory model_data
```
