### ISSUE TITLE
运行app.py时报错

### ISSUE THREAD

**Issue by adysloud** [zhaoyingjun/chatbot#144]
报错信息：
`Traceback (most recent call last):
  File "E:\python机器学习资料\chatbot-master\Chatbot-tensowflow2.0\Seq2seqchatbot\web\app.py", line 6, in <module>
    import execute
  File "E:\python机器学习资料\chatbot-master\Chatbot-tensowflow2.0\Seq2seqchatbot\execute.py", line 62, in <module>
    input_tensor, input_token, target_tensor, target_token = read_data(gConfig['seq_data'])
  File "E:\python机器学习资料\chatbot-master\Chatbot-tensowflow2.0\Seq2seqchatbot\execute.py", line 47, in read_data
    target_tensor = tf.keras.preprocessing.sequence.pad_sequences(target_tensor, maxlen=max_length_tar,
  File "D:\conda\lib\site-packages\keras\utils\data_utils.py", line 1041, in pad_sequences
    trunc = np.asarray(trunc, dtype=dtype)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
`

target_tensor type为list，内容一大串

**Comment by wenChingzhou** [comment]
怎么解决的呢
