### ISSUE TITLE
pytorch模型中，执行execute.py ,提示没有seq.data

### ISSUE THREAD

**Issue by luckfu** [zhaoyingjun/chatbot#148]
python ./execute.py
Traceback (most recent call last):
  File "/Users//chatbot/Chatbot_pytorch/Seq2seqchatbot/./execute.py", line 81, in <module>
    input_tensor,input_lang,target_tensor,target_lang= read_data(gConfig['seq_data'], gConfig['max_train_data_size'])
  File "/Users//chatbot/Chatbot_pytorch/Seq2seqchatbot/./execute.py", line 74, in read_data
    input_lang,target_lang,pairs=create_dataset(path,num_examples)
  File "/Users/chatbot/Chatbot_pytorch/Seq2seqchatbot/./execute.py", line 25, in create_dataset
    lines = io.open(path, encoding='UTF-8').read().strip().split('\n')
FileNotFoundError: [Errno 2] No such file or directory: 'train_data/seq.data'

**Comment by luckfu** [comment]
知道问题了，配置里语料文件不正确的时候，data_util.py没有提示就退出了，所以预处理没有执行

**Comment by visoeclipse** [comment]
> 知道问题了，配置里语料文件不正确的时候，data_util.py没有提示就退出了，所以预处理没有执行

新手问下，配置错在哪？

**Comment by ubbm** [comment]
你好，怎么解决这个问题，是要换语料文件吗？
