### ISSUE TITLE
聊天报错error calling function:AttributeError: module 'execute' has no attribute 'predict'

### ISSUE THREAD

**Issue by Umamusume-Agnes-Digital** [zhaoyingjun/chatbot#149]
步骤：readme里步骤1和2，到启动app.py步骤后，打开网页，聊天失败`error calling function`后台报错
![image](https://user-images.githubusercontent.com/70925546/208605995-bc8bbab4-321e-427c-9a53-4e184edb6e2c.png)

```
 * Running on http://192.168.3.201:8808/ (Press CTRL+C to quit)
192.168.3.201 - - [20/Dec/2022 15:09:45] "GET / HTTP/1.1" 200 -
192.168.3.201 - - [20/Dec/2022 15:09:45] "GET /static/css/normalize.css HTTP/1.1" 304 -
192.168.3.201 - - [20/Dec/2022 15:09:45] "GET /static/css/style.css HTTP/1.1" 304 -
192.168.3.201 - - [20/Dec/2022 15:09:45] "GET /static/js/jquery.mCustomScrollbar.min.css HTTP/1.1" 304 -
192.168.3.201 - - [20/Dec/2022 15:09:45] "GET /static/js/jquery-latest.js HTTP/1.1" 304 -
192.168.3.201 - - [20/Dec/2022 15:09:45] "GET /static/js/jquery.min.js HTTP/1.1" 304 -
192.168.3.201 - - [20/Dec/2022 15:09:45] "GET /static/js/jquery.mCustomScrollbar.concat.min.js HTTP/1.1" 304 -
192.168.3.201 - - [20/Dec/2022 15:09:45] "GET /static/js/index.js HTTP/1.1" 304 -
192.168.3.201 - - [20/Dec/2022 15:09:45] "GET /static/res/easybot.png HTTP/1.1" 304 -
192.168.3.201 - - [20/Dec/2022 15:09:45] "GET /static/res/hd2.jpg HTTP/1.1" 404 -
Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\73580\AppData\Local\Temp\jieba.cache
Loading model cost 0.461 seconds.
Prefix dict has been built successfully.
[2022-12-20 15:09:49,381] ERROR in app: Exception on /message [POST]
Traceback (most recent call last):
  File "D:\python3.9.10\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\python3.9.10\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\python3.9.10\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\python3.9.10\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "D:\python3.9.10\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\python3.9.10\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "e:\text\github\deep\chatbot\Chatbot_pytorch\Seq2seqchatbot\web\app.py", line 43, in reply
    res_msg = execute.predict(req_msg)
AttributeError: module 'execute' has no attribute 'predict'
192.168.3.201 - - [20/Dec/2022 15:09:49] "POST /message HTTP/1.1" 500 -
2022-12-20 15:10:40 - heartbeat
2022-12-20 15:11:40 - heartbeat
2022-12-20 15:12:40 - heartbeat
2022-12-20 15:13:40 - heartbeat
[2022-12-20 15:14:11,415] ERROR in app: Exception on /message [POST]
Traceback (most recent call last):
  File "D:\python3.9.10\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\python3.9.10\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\python3.9.10\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\python3.9.10\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "D:\python3.9.10\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\python3.9.10\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "e:\text\github\deep\chatbot\Chatbot_pytorch\Seq2seqchatbot\web\app.py", line 43, in reply
    res_msg = execute.predict(req_msg)
AttributeError: module 'execute' has no attribute 'predict'
192.168.3.201 - - [20/Dec/2022 15:14:11] "POST /message HTTP/1.1" 500 -
```

已确保环境
torch==1.11.0
flask==0.11.1

**Comment by Umamusume-Agnes-Digital** [comment]
现在遇到的问题是找不到'train_data/seq.data'目录
我错误的以为execute是一个库，但是其实是上级目录里的execute.py
```
Traceback (most recent call last):
  File "e:\text\github\deep\chatbot\Chatbot_pytorch\Seq2seqchatbot\web\app.py", line 7, in <module>
    import execute
  File "E:\text\github\deep\chatbot\Chatbot_pytorch\Seq2seqchatbot\web\..\execute.py", line 81, in <module>
    input_tensor,input_lang,target_tensor,target_lang= read_data(gConfig['seq_data'], gConfig['max_train_data_size'])
  File "E:\text\github\deep\chatbot\Chatbot_pytorch\Seq2seqchatbot\web\..\execute.py", line 74, in read_data
    input_lang,target_lang,pairs=create_dataset(path,num_examples)
  File "E:\text\github\deep\chatbot\Chatbot_pytorch\Seq2seqchatbot\web\..\execute.py", line 25, in create_dataset
    lines = io.open(path, encoding='UTF-8').read().strip().split('\n')
FileNotFoundError: [Errno 2] No such file or directory: 'train_data/seq.data'
```

**Comment by Umamusume-Agnes-Digital** [comment]
上述问题通过简单粗暴的移动文件夹完成，接下来是这个报错
request下没有is_xhr的值
```
[2022-12-20 21:40:48,809] ERROR in app: Exception on /message [POST]
Traceback (most recent call last):
  File "D:\python3.9.10\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\python3.9.10\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\python3.9.10\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\python3.9.10\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "D:\python3.9.10\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\python3.9.10\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "e:\text\github\deep\chatbot\Chatbot_pytorch\Seq2seqchatbot\app.py", line 52, in reply
    return jsonify( { 'text': res_msg } )
  File "D:\python3.9.10\lib\site-packages\flask\json.py", line 254, in jsonify
    if current_app.config['JSONIFY_PRETTYPRINT_REGULAR'] and not request.is_xhr:
AttributeError: 'Request' object has no attribute 'is_xhr'
127.0.0.1 - - [20/Dec/2022 21:40:48] "POST /message HTTP/1.1" 500 -
```

**Comment by Umamusume-Agnes-Digital** [comment]
在python==3.9的情况下，flask需要更新版本，我安装flask==2.2.2的时候，正常启动

**Comment by sunyrain** [comment]
> 现在遇到的问题是找不到'train_data/seq.data'目录 我错误的以为execute是一个库，但是其实是上级目录里的execute.py
> 
> ```
> Traceback (most recent call last):
>   File "e:\text\github\deep\chatbot\Chatbot_pytorch\Seq2seqchatbot\web\app.py", line 7, in <module>
>     import execute
>   File "E:\text\github\deep\chatbot\Chatbot_pytorch\Seq2seqchatbot\web\..\execute.py", line 81, in <module>
>     input_tensor,input_lang,target_tensor,target_lang= read_data(gConfig['seq_data'], gConfig['max_train_data_size'])
>   File "E:\text\github\deep\chatbot\Chatbot_pytorch\Seq2seqchatbot\web\..\execute.py", line 74, in read_data
>     input_lang,target_lang,pairs=create_dataset(path,num_examples)
>   File "E:\text\github\deep\chatbot\Chatbot_pytorch\Seq2seqchatbot\web\..\execute.py", line 25, in create_dataset
>     lines = io.open(path, encoding='UTF-8').read().strip().split('\n')
> FileNotFoundError: [Errno 2] No such file or directory: 'train_data/seq.data'
> ```

这个怎么移动文件夹解决a?
