### ISSUE TITLE
关于导入配置文件时gbk编码出错问题的解决

### ISSUE THREAD

**Issue by XingyuXiong** [zhaoyingjun/chatbot#44]
报错详细信息如下
Traceback (most recent call last):
  File "data_utls.py", line 13, in <module>
    gConfig=getConfig.get_config()
  File "C:\Users\53194\Desktop\chatbot-master\seq2seqChatbot\getConfig.py", line 29, in get_config
    parser.read(config_file)
  File "C:\Users\53194\AppData\Local\Programs\Python\Python37-32\lib\configparser.py", line 696, in read
    self._read(fp, filename)
  File "C:\Users\53194\AppData\Local\Programs\Python\Python37-32\lib\configparser.py", line 1014, in _read
    for lineno, line in enumerate(fp, start=1):
UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 69: illegal multibyte sequence

明显是在读seq2seq.ini时出错，经测试发现是中文注释问题。如果发现该错误，删去该文件中所有中文注释即可。

**Comment by zhaoyingjun** [comment]
或者修改成utf-8编码也可以

**Comment by XingyuXiong** [comment]
以utf-8的格式重新存储吗？

**Comment by XingyuXiong** [comment]
以utf-8的格式重新存储吗？
