### ISSUE TITLE
TF2.0中缺少checkpoint.dir文件。

### ISSUE THREAD

**Issue by Leopold-Fitz-AI** [zhaoyingjun/chatbot#85]
Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/chatbot-master/chineseChatbotWeb-tf2.0/execute.py", line 137, in <module>
    train()
  File "C:/Users/Administrator/Desktop/chatbot-master/chineseChatbotWeb-tf2.0/execute.py", line 62, in train
    ckpt=tf.io.gfile.listdir(checkpoint_dir)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\tensorflow_core\python\lib\io\file_io.py", line 640, in list_directory_v2
    message="Could not find directory {}".format(path))
tensorflow.python.framework.errors_impl.NotFoundError: Could not find directory model_data
看了之前作者和一位先生对话中，找到了working_dir,但是没有checkpoint_dir，把其修改为checkpoint放入配置中也找不到，求指教，谢谢。

**Comment by somebodydie** [comment]
是的，同样有这个问题

**Comment by zhaoyingjun** [comment]
checkpoint_dir 是一个参数，我在linux系统上没有这个问题。你如果出现这个问题你直接把文件夹的路径传入ckpt=tf.io.gfile.listdir（）也可以，比如ckpt=tf.io.gfile.listdir("/C:/Users/Administrator/Desktop/chatbot-master/chineseChatbotWeb-tf2.0/model_data")

**Comment by wxiaoli** [comment]
项目目录里建一个名为 model_data 的文件夹就好了
