### ISSUE TITLE
python新手，求教大佬们，我运行项目的时候报这个错是为什么呢

### ISSUE THREAD

**Issue by nuandongtuzi** [zhaoyingjun/chatbot#95]
D:\DevelopTools\anaconda3\envs\chatbot\python.exe D:/projectFile/chatbot-master/chineseChatbotWeb-tf2.0/seq2seqChatbot/data_util.py
Traceback (most recent call last):
  File "D:\DevelopTools\anaconda3\envs\chatbot\lib\configparser.py", line 846, in items
    d.update(self._sections[section])
KeyError: 'ints'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/projectFile/chatbot-master/chineseChatbotWeb-tf2.0/seq2seqChatbot/data_util.py", line 13, in <module>
    gConfig=getConfig.get_config()
  File "D:\projectFile\chatbot-master\chineseChatbotWeb-tf2.0\seq2seqChatbot\getConfig.py", line 8, in get_config
    _conf_ints = [ (key, int(value)) for key,value in parser.items('ints') ]
  File "D:\DevelopTools\anaconda3\envs\chatbot\lib\configparser.py", line 849, in items
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'ints'

Process finished with exit code 1

**Comment by nuandongtuzi** [comment]
已解决谢谢

**Comment by azhou123456** [comment]
你好。小白同问，怎么解决的？

**Comment by OIGrass** [comment]
你好，能指导一下怎么解决的吗
