### ISSUE TITLE
nosection 报错

### ISSUE THREAD

**Issue by UnicornJin** [zhaoyingjun/chatbot#97]
作者你好！
我用不同方式尝试启动程序
但是在data_util.py就产生了报错：
![image](https://user-images.githubusercontent.com/47232548/98067285-34842280-1e94-11eb-8a34-3e1c0b279f8e.png)
请问您知道原因吗?

**Comment by UnicornJin** [comment]
似乎是.ini文件没有被程序识别?

**Comment by Dennis174698** [comment]
我也有同样的错误

**Comment by Dennis174698** [comment]
![Screenshot from 2020-11-08 14-55-45](https://user-images.githubusercontent.com/32445088/98459117-8bf6fb00-21d2-11eb-83be-ad8a933227b8.png)
我解决了，这里的名字你改了吗

> 似乎是.ini文件没有被程序识别?

**Comment by UnicornJin** [comment]
> ![Screenshot from 2020-11-08 14-55-45](https://user-images.githubusercontent.com/32445088/98459117-8bf6fb00-21d2-11eb-83be-ad8a933227b8.png)
> 我解决了，这里的名字你改了吗
> 
> > 似乎是.ini文件没有被程序识别?

请问这个是哪个文件的第几行呀
我没找到这个地方哈哈

**Comment by Dennis174698** [comment]
在getconfig.py里

**Comment by zhaoyingjun** [comment]
这是因为配置文件里 没有int 这个section，检查一下 加上来就可以里

**Comment by UnicornJin** [comment]
> 这是因为配置文件里 没有int 这个section，检查一下 加上来就可以里

Hi, 您好，我刚刚试了一下，可以运行了，但是打开url之后输入语句再点send, 报了function error。
命令行里面报错是：
_pickle.UnpicklingError: invalid load key, '\xe5'.
请问您知道是为啥吗？

**Comment by UnicornJin** [comment]
> > 这是因为配置文件里 没有int 这个section，检查一下 加上来就可以里
> 
> Hi, 您好，我刚刚试了一下，可以运行了，但是打开url之后输入语句再点send, 报了function error。
> 命令行里面报错是：
> _pickle.UnpicklingError: invalid load key, '\xe5'.
> 请问您知道是为啥吗？

完整报错是这样的：

[2020-11-08 22:22:05,433] ERROR in app: Exception on /message [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 41, in reply
    res_msg = execute.predict(req_msg)
  File "/home/pi/chatbot/chineseChatbotWeb-pytorch/seq2seqChatbot/execute.py", line 139, in predict
    checkpoint=torch.load(checkpoint_prefix)
  File "/usr/local/lib/python3.6/site-packages/torch/serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.6/site-packages/torch/serialization.py", line 765, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\xe5'.

**Comment by Misaka17032** [comment]
改utf-8.你这是gbk的错误。
